---
- name: Configure kibana
  become: true
  template:
    src: kibana.yml.j2
    mode: 0666
    dest: /etc/kibana/kibana.yml
# - name: change permissions
#   become: true
#   path: /etc/kibana/kibana.yml
#   # owner: kibana
#   group: kibana
#   mode: 0644
#   notify: restart kibana
  