---
- name: "Check that kibanas's deb is exists"
  stat:
    path: "{{ pkg_tmp_src }}/kibana-{{ kibana_version }}-amd64.deb"
  register: stat_result
  delegate_to: localhost
- name: "Download kibana's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-amd64.deb"
    dest: "{{ pkg_tmp_src }}/kibana-{{ kibana_version }}-amd64.deb"
    validate_certs: false
  delegate_to: localhost
  register: download_kibana
  until: download_kibana is succeeded
  when: 
  - not stat_result.stat.exists
  - kibana_install_type == 'remote'
- name: Copy kibana to manage host
  copy:
    src: "{{ pkg_tmp_src }}/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0755
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
